version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql-container-2
    environment:
      MYSQL_ROOT_PASSWORD: Dimaria123
    volumes:
      - mysql_data_existing:/var/lib/mysql
      - ~/mysql-conf/my.cnf:/etc/mysql/conf.d/my.cnf:ro
    ports:
      - 3306:3306
    networks:
      - app-net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: Dimaria123
    networks:
      - app-net
    ports:
      - "8083:80"

volumes:
  mysql_data_existing:
    external: true

networks:
  app-net:
    driver: bridge

